run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - gocritic
    - gofmt
    - revive
    - gocyclo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
  max-issues-per-linter: 50
  max-same-issues: 10

linters-settings:
  gocyclo:
    min-complexity: 15
